-- Migration 027: Relax FK constraint on siphox_kit_orders.siphox_customer_id
--
-- The original FK constraint (migration 020) requires every siphox_kit_orders row
-- to have a matching siphox_customers row. However, the fulfillment orchestration
-- (lib/siphox/fulfillment.ts) needs to insert kit order rows BEFORE the SiPhox
-- customer exists — e.g., when intake data is not yet available (pending_intake)
-- or when the SiPhox API fails on customer creation (pending_fulfillment).
--
-- These rows use siphox_customer_id = 'pending' as a placeholder, which violates
-- the FK constraint and causes silent data loss (the top-level try/catch in
-- triggerSiphoxFulfillment swallows the DB error).
--
-- Fix: Drop the FK constraint so deferred/pending orders can be stored.
-- The application code already handles the 'pending' → real ID transition
-- via updateFulfillmentStatus when the order is eventually fulfilled.

-- Drop the FK constraint (name is auto-generated by Postgres)
DO $$
DECLARE
  fk_name TEXT;
BEGIN
  SELECT constraint_name INTO fk_name
  FROM information_schema.table_constraints
  WHERE table_name = 'siphox_kit_orders'
    AND constraint_type = 'FOREIGN KEY'
    AND constraint_name LIKE '%siphox_customer_id%'
  LIMIT 1;

  IF fk_name IS NOT NULL THEN
    EXECUTE 'ALTER TABLE siphox_kit_orders DROP CONSTRAINT ' || fk_name;
    RAISE NOTICE 'Dropped FK constraint: %', fk_name;
  ELSE
    RAISE NOTICE 'No FK constraint found on siphox_kit_orders.siphox_customer_id — may already be dropped';
  END IF;
END $$;

-- Also drop the FK on siphox_reports for consistency (same pattern applies
-- if reports are ever cached before customer row exists)
DO $$
DECLARE
  fk_name TEXT;
BEGIN
  SELECT constraint_name INTO fk_name
  FROM information_schema.table_constraints
  WHERE table_name = 'siphox_reports'
    AND constraint_type = 'FOREIGN KEY'
    AND constraint_name LIKE '%siphox_customer_id%'
  LIMIT 1;

  IF fk_name IS NOT NULL THEN
    EXECUTE 'ALTER TABLE siphox_reports DROP CONSTRAINT ' || fk_name;
    RAISE NOTICE 'Dropped FK constraint on siphox_reports: %', fk_name;
  ELSE
    RAISE NOTICE 'No FK constraint found on siphox_reports.siphox_customer_id — may already be dropped';
  END IF;
END $$;
