-- Migration 047: Remove stale COLESIDNER / COLESIDNER10 affiliate codes for Cole Sidner
-- These were auto-generated by the staging provisioning system which derived the code
-- from the email (cole.sidner@gmail.com → "Cole.sidner" → "COLESIDNER") instead of
-- using the proper full_name split ("Cole Sidner" → "SIDNER").
-- The correct codes are COLE (membership, primary) and COLE10 (product, secondary),
-- created by migrations 041 + 046.

-- Step 1: Delete the stale codes entirely (no historical orders reference them)
DELETE FROM affiliate_codes WHERE lower(code) IN ('colesidner', 'colesidner10');

-- Step 2: Ensure COLE is the primary membership code
UPDATE affiliate_codes
SET is_primary = TRUE, code_type = 'membership', active = TRUE, updated_at = NOW()
WHERE lower(code) = 'cole'
  AND creator_id = (SELECT id FROM creators WHERE lower(email) = 'cole.sidner@gmail.com');

-- Step 3: Ensure COLE10 is the secondary product code
UPDATE affiliate_codes
SET is_primary = FALSE, code_type = 'product', active = TRUE, updated_at = NOW()
WHERE lower(code) = 'cole10'
  AND creator_id = (SELECT id FROM creators WHERE lower(email) = 'cole.sidner@gmail.com');
