// Product Catalog for Members Shop
// Quick Order catalog with peptide product data

export type ProductCategory =
  | 'growth_factor'
  | 'repair'
  | 'metabolic'
  | 'bioregulator'
  | 'neuropeptide'
  | 'immune'
  | 'hormonal'
  | 'blend'
  | 'accessory'
  | 'wellness_supplement'

export type StockStatus = 'in_stock' | 'low_stock' | 'out_of_stock'

export type ProductVariant = {
  label: string
  value: string
}

export type ShopProduct = {
  sku: string
  name: string
  peptideId: string | null
  doseMg: number
  volumeMl: number
  category: ProductCategory
  isBlend: boolean
  blendComponents?: string[]
  description?: string
  priceUsd?: number
  imageUrl?: string
  stockStatus: StockStatus
  bulkPrice?: number
  bulkMinQty?: number
  bulkSavePercent?: number
  variants: ProductVariant[]
  defaultVariant: string
  vialType?: '3ML' | '5ML' | '10ML' | '30ML'
}

// ===================================================
// Product Catalog — prices include 70% markup
// ===================================================

export const PRODUCT_CATALOG: ShopProduct[] = [
  {
    sku: '5AMINO1MQ-5MG-3ML',
    name: '5-Amino-1mq',
    peptideId: '5-amino-1mq',
    doseMg: 5,
    volumeMl: 3,
    category: 'metabolic',
    isBlend: false,
    description: 'Inhibits NNMT enzyme to boost cellular energy metabolism and support fat loss. Ideal for metabolic optimization protocols.',
    priceUsd: 76.50,
    stockStatus: 'in_stock',
    variants: [
      { label: '5mg - 3ML', value: '5mg-3ml' },
      { label: '50mg - 3ML', value: '50mg-3ml' },
      { label: '50mg - 5ML', value: '50mg-5ml' },
    ],
    defaultVariant: '5mg-3ml',
    vialType: '3ML',
  },
  {
    sku: 'AOD9604-5MG-3ML',
    name: 'AOD-9604',
    peptideId: 'aod-9604',
    doseMg: 5,
    volumeMl: 3,
    category: 'metabolic',
    isBlend: false,
    description: 'Growth hormone fragment that stimulates lipolysis and inhibits lipogenesis. Supports targeted fat reduction without affecting blood sugar.',
    priceUsd: 93.50,
    stockStatus: 'in_stock',
    variants: [
      { label: '5mg - 3ML', value: '5mg-3ml' },
      { label: '10mg - 3ML', value: '10mg-3ml' },
    ],
    defaultVariant: '5mg-3ml',
    vialType: '3ML',
  },
  {
    sku: 'BLND-AOD9604CJC1295IPAMORELIN-3ML',
    name: 'AOD-9604 | CJC-1295 | Ipamorelin',
    peptideId: null,
    doseMg: 10,
    volumeMl: 3,
    category: 'metabolic',
    isBlend: true,
    blendComponents: ['aod-9604', 'cjc-1295', 'ipamorelin'],
    description: 'Triple-action blend combining fat loss, growth hormone release, and appetite regulation for comprehensive body recomposition.',
    priceUsd: 136.00,
    stockStatus: 'in_stock',
    variants: [
      { label: '10mg/5mg/5mg - 3ML', value: '10mg-5mg-5mg-3ml' },
    ],
    defaultVariant: '10mg-5mg-5mg-3ml',
    vialType: '3ML',
  },
  {
    sku: 'ARA290-10MG-3ML',
    name: 'ARA-290',
    peptideId: 'ara-290',
    doseMg: 10,
    volumeMl: 3,
    category: 'neuropeptide',
    isBlend: false,
    description: 'Neuroprotective peptide that targets innate repair receptors to reduce inflammation and support nerve regeneration.',
    priceUsd: 100.30,
    stockStatus: 'in_stock',
    variants: [
      { label: '10mg - 3ML', value: '10mg-3ml' },
    ],
    defaultVariant: '10mg-3ml',
    vialType: '3ML',
  },
  {
    sku: 'BACWATER-30ML',
    name: 'Bacteriostatic Water',
    peptideId: 'bacteriostatic-water',
    doseMg: 0,
    volumeMl: 30,
    category: 'accessory',
    isBlend: false,
    description: 'Sterile water with 0.9% benzyl alcohol for safe reconstitution of lyophilized peptides.',
    priceUsd: 17.00,
    stockStatus: 'in_stock',
    variants: [{ label: '30ml', value: '30ml' }],
    defaultVariant: '30ml',
    vialType: '30ML',
  },
  {
    sku: 'BPC157-5MG-3ML',
    name: 'BPC-157',
    peptideId: 'bpc-157',
    doseMg: 5,
    volumeMl: 3,
    category: 'repair',
    isBlend: false,
    description: 'Body Protection Compound that accelerates healing of tendons, ligaments, muscles, and gut lining. Widely used for injury recovery.',
    priceUsd: 78.20,
    stockStatus: 'in_stock',
    bulkPrice: 69.70,
    bulkMinQty: 25,
    bulkSavePercent: 11,
    variants: [
      { label: '5mg - 3ML', value: '5mg-3ml' },
      { label: '10mg - 3ML', value: '10mg-3ml' },
      { label: '15mg - 3ML', value: '15mg-3ml' },
      { label: '15mg - 5ML', value: '15mg-5ml' },
    ],
    defaultVariant: '5mg-3ml',
    vialType: '3ML',
  },
  {
    sku: 'BPC157-TB500-5MG-3ML',
    name: 'BPC-157 | TB-500',
    peptideId: null,
    doseMg: 5,
    volumeMl: 3,
    category: 'blend',
    isBlend: true,
    blendComponents: ['bpc-157', 'tb-500'],
    description: 'Synergistic repair blend combining tissue healing and systemic anti-inflammatory action for accelerated recovery.',
    priceUsd: 83.30,
    stockStatus: 'in_stock',
    bulkPrice: 76.50,
    bulkMinQty: 25,
    bulkSavePercent: 8,
    variants: [
      { label: '5mg/5mg - 3ML', value: '5mg-5mg-3ml' },
      { label: '10mg/10mg - 3ML', value: '10mg-10mg-3ml' },
      { label: '10mg/10mg - 5ML', value: '10mg-10mg-5ml' },
    ],
    defaultVariant: '5mg-5mg-3ml',
    vialType: '3ML',
  },
  {
    sku: 'CAGRILINTIDE-5MG-3ML',
    name: 'Cagrilintide',
    peptideId: 'glp1-cagrilintide',
    doseMg: 5,
    volumeMl: 3,
    category: 'metabolic',
    isBlend: false,
    description: 'Long-acting amylin analog that reduces appetite and enhances satiety. Supports sustained weight management.',
    priceUsd: 153.00,
    stockStatus: 'in_stock',
    bulkPrice: 136.00,
    bulkMinQty: 25,
    bulkSavePercent: 11,
    variants: [
      { label: '5mg - 3ML', value: '5mg-3ml' },
      { label: '10mg - 3ML', value: '10mg-3ml' },
    ],
    defaultVariant: '5mg-3ml',
    vialType: '3ML',
  },
  {
    sku: 'CJC1295-5MG-3ML',
    name: 'CJC-1295',
    peptideId: 'cjc-1295',
    doseMg: 5,
    volumeMl: 3,
    category: 'growth_factor',
    isBlend: false,
    description: 'Growth hormone-releasing hormone analog that stimulates natural GH production for improved recovery, sleep, and body composition.',
    priceUsd: 76.50,
    stockStatus: 'in_stock',
    bulkPrice: 69.70,
    bulkMinQty: 25,
    bulkSavePercent: 9,
    variants: [
      { label: '5mg - 3ML', value: '5mg-3ml' },
      { label: '10mg - 3ML', value: '10mg-3ml' },
      { label: '15mg - 5ML', value: '15mg-5ml' },
    ],
    defaultVariant: '5mg-3ml',
    vialType: '3ML',
  },
  {
    sku: 'CJC1295DAC-5MG-3ML',
    name: 'CJC-1295 W/ DAC',
    peptideId: 'cjc-1295-dac',
    doseMg: 5,
    volumeMl: 3,
    category: 'growth_factor',
    isBlend: false,
    description: 'Extended half-life GHRH analog with Drug Affinity Complex for sustained growth hormone elevation over days.',
    priceUsd: 76.50,
    stockStatus: 'in_stock',
    bulkPrice: 69.70,
    bulkMinQty: 25,
    bulkSavePercent: 9,
    variants: [{ label: '5mg - 3ML', value: '5mg-3ml' }],
    defaultVariant: '5mg-3ml',
    vialType: '3ML',
  },
  {
    sku: 'CJC1295-IPAMORELIN-5MG-3ML',
    name: 'CJC-1295 | Ipamorelin',
    peptideId: null,
    doseMg: 5,
    volumeMl: 3,
    category: 'growth_factor',
    isBlend: true,
    blendComponents: ['cjc-1295', 'ipamorelin'],
    description: 'Gold-standard GH stack combining GHRH and GHRP pathways for amplified growth hormone release with minimal side effects.',
    priceUsd: 93.50,
    stockStatus: 'in_stock',
    bulkPrice: 83.30,
    bulkMinQty: 25,
    bulkSavePercent: 11,
    variants: [
      { label: '5mg/5mg - 3ML', value: '5mg-5mg-3ml' },
      { label: '10mg/10mg - 3ML', value: '10mg-10mg-3ml' },
      { label: '12mg/6mg - 5ML', value: '12mg-6mg-5ml' },
    ],
    defaultVariant: '5mg-5mg-3ml',
    vialType: '3ML',
  },
  {
    sku: 'DSIP-10MG-3ML',
    name: 'DSIP',
    peptideId: 'dsip',
    doseMg: 10,
    volumeMl: 3,
    category: 'bioregulator',
    isBlend: false,
    description: 'Delta Sleep-Inducing Peptide that promotes deep, restorative sleep and helps normalize circadian rhythm disruptions.',
    priceUsd: 79.90,
    stockStatus: 'in_stock',
    bulkPrice: 71.40,
    bulkMinQty: 25,
    bulkSavePercent: 11,
    variants: [
      { label: '5mg - 3ML', value: '5mg-3ml' },
      { label: '10mg - 3ML', value: '10mg-3ml' },
      { label: '15mg - 3ML', value: '15mg-3ml' },
    ],
    defaultVariant: '10mg-3ml',
    vialType: '3ML',
  },
  {
    sku: 'EPITHALON-10MG-3ML',
    name: 'Epithalon',
    peptideId: 'epitalon',
    doseMg: 10,
    volumeMl: 3,
    category: 'bioregulator',
    isBlend: false,
    description: 'Telomerase-activating peptide that supports cellular longevity and may slow biological aging processes.',
    priceUsd: 66.30,
    stockStatus: 'in_stock',
    bulkPrice: 59.50,
    bulkMinQty: 25,
    bulkSavePercent: 10,
    variants: [
      { label: '10mg - 3ML', value: '10mg-3ml' },
      { label: '50mg - 3ML', value: '50mg-3ml' },
      { label: '50mg - 5ML', value: '50mg-5ml' },
    ],
    defaultVariant: '10mg-3ml',
    vialType: '3ML',
  },
  {
    sku: 'FOLLISTATIN-1MG-3ML',
    name: 'Follistatin',
    peptideId: 'follistatin-344',
    doseMg: 1,
    volumeMl: 3,
    category: 'growth_factor',
    isBlend: false,
    description: 'Myostatin inhibitor that promotes lean muscle growth and may enhance muscle development beyond genetic potential.',
    priceUsd: 187.00,
    stockStatus: 'in_stock',
    bulkPrice: 178.50,
    bulkMinQty: 25,
    bulkSavePercent: 5,
    variants: [{ label: '1mg - 3ML', value: '1mg-3ml' }],
    defaultVariant: '1mg-3ml',
    vialType: '3ML',
  },
  {
    sku: 'GHKCU-50MG-3ML',
    name: 'GHK-CU',
    peptideId: 'ghk-cu',
    doseMg: 50,
    volumeMl: 3,
    category: 'repair',
    isBlend: false,
    description: 'Copper peptide that stimulates collagen synthesis, accelerates wound healing, and promotes skin rejuvenation and hair growth.',
    priceUsd: 74.80,
    stockStatus: 'in_stock',
    bulkPrice: 68.00,
    bulkMinQty: 25,
    bulkSavePercent: 9,
    variants: [
      { label: '50mg - 3ML', value: '50mg-3ml' },
      { label: '70mg - 5ML', value: '70mg-5ml' },
      { label: '100mg - 3ML', value: '100mg-3ml' },
      { label: '100mg - 10ML', value: '100mg-10ml' },
    ],
    defaultVariant: '50mg-3ml',
    vialType: '3ML',
  },
  {
    sku: 'GHRP2-5MG-3ML',
    name: 'GHRP-2',
    peptideId: 'ghrp-2',
    doseMg: 5,
    volumeMl: 3,
    category: 'growth_factor',
    isBlend: false,
    description: 'Potent growth hormone secretagogue that stimulates GH release and increases appetite. Supports muscle gain and recovery.',
    priceUsd: 59.50,
    stockStatus: 'in_stock',
    bulkPrice: 54.40,
    bulkMinQty: 25,
    bulkSavePercent: 9,
    variants: [
      { label: '5mg - 3ML', value: '5mg-3ml' },
      { label: '10mg - 3ML', value: '10mg-3ml' },
    ],
    defaultVariant: '5mg-3ml',
    vialType: '3ML',
  },
  {
    sku: 'GHRP6-5MG-3ML',
    name: 'GHRP-6',
    peptideId: 'ghrp-6',
    doseMg: 5,
    volumeMl: 3,
    category: 'growth_factor',
    isBlend: false,
    description: 'Growth hormone-releasing peptide that strongly stimulates appetite and GH secretion. Ideal for recovery and lean mass gains.',
    priceUsd: 59.50,
    stockStatus: 'in_stock',
    bulkPrice: 54.40,
    bulkMinQty: 25,
    bulkSavePercent: 9,
    variants: [
      { label: '5mg - 3ML', value: '5mg-3ml' },
      { label: '10mg - 3ML', value: '10mg-3ml' },
    ],
    defaultVariant: '5mg-3ml',
    vialType: '3ML',
  },
  {
    sku: 'GLOW-BPC157-GHKCU-TB500-3ML',
    name: 'GLOW BPC-157 GHK-CU TB-500',
    peptideId: null,
    doseMg: 10,
    volumeMl: 3,
    category: 'blend',
    isBlend: true,
    blendComponents: ['bpc-157', 'ghk-cu', 'tb-500'],
    description: 'Premium repair and rejuvenation blend targeting tissue healing, collagen production, and skin vitality.',
    priceUsd: 178.50,
    stockStatus: 'in_stock',
    bulkPrice: 161.50,
    bulkMinQty: 25,
    bulkSavePercent: 10,
    variants: [
      { label: '10mg/50mg/10mg - 3ML', value: '10mg-50mg-10mg-3ml' },
      { label: '10mg/70mg/10mg - 5ML', value: '10mg-70mg-10mg-5ml' },
    ],
    defaultVariant: '10mg-50mg-10mg-3ml',
    vialType: '3ML',
  },
  {
    sku: 'GLP1-CAGRILINTIDE-SMA-3ML',
    name: 'GLP 1 Cagrilintide | SMA',
    peptideId: null,
    doseMg: 2.5,
    volumeMl: 3,
    category: 'metabolic',
    isBlend: true,
    blendComponents: ['glp1-cagrilintide', 'glp1-semaglutide'],
    description: 'Dual-agonist weight management blend combining amylin and GLP-1 receptor activation for enhanced appetite suppression.',
    priceUsd: 153.00,
    stockStatus: 'in_stock',
    bulkPrice: 137.70,
    bulkMinQty: 25,
    bulkSavePercent: 10,
    variants: [
      { label: '2.5mg/2.5mg - 3ML', value: '2.5mg-2.5mg-3ml' },
      { label: '5mg/5mg - 3ML', value: '5mg-5mg-3ml' },
      { label: '10mg/10mg - 3ML', value: '10mg-10mg-3ml' },
    ],
    defaultVariant: '2.5mg-2.5mg-3ml',
    vialType: '3ML',
  },
  {
    sku: 'GLP1-SV-10MG-3ML',
    name: 'GLP-1 SV',
    peptideId: 'glp1-sv',
    doseMg: 10,
    volumeMl: 3,
    category: 'metabolic',
    isBlend: false,
    description: 'GLP-1 receptor agonist that regulates blood sugar and appetite. Supports significant weight loss outcomes.',
    priceUsd: 188.70,
    stockStatus: 'low_stock',
    bulkPrice: 176.80,
    bulkMinQty: 25,
    bulkSavePercent: 6,
    variants: [{ label: '10mg - 3ML', value: '10mg-3ml' }],
    defaultVariant: '10mg-3ml',
    vialType: '3ML',
  },
  {
    sku: 'GLP1-MZ-5MG-3ML',
    name: 'GLP-1 MZ',
    peptideId: 'glp1-mz',
    doseMg: 5,
    volumeMl: 3,
    category: 'metabolic',
    isBlend: false,
    description: 'GLP-1 analog supporting metabolic health through improved insulin sensitivity and appetite regulation.',
    priceUsd: 153.00,
    stockStatus: 'in_stock',
    variants: [
      { label: '5mg - 3ML', value: '5mg-3ml' },
      { label: '10mg - 3ML', value: '10mg-3ml' },
    ],
    defaultVariant: '5mg-3ml',
    vialType: '3ML',
  },
  {
    sku: 'GONADORELIN-2MG-3ML',
    name: 'Gonadorelin',
    peptideId: 'gonadorelin',
    doseMg: 2,
    volumeMl: 3,
    category: 'hormonal',
    isBlend: false,
    description: 'GnRH agonist that stimulates natural production of LH and FSH. Used to maintain fertility during hormone therapy.',
    priceUsd: 76.50,
    stockStatus: 'in_stock',
    bulkPrice: 69.70,
    bulkMinQty: 25,
    bulkSavePercent: 9,
    variants: [{ label: '2mg - 3ML', value: '2mg-3ml' }],
    defaultVariant: '2mg-3ml',
    vialType: '3ML',
  },
  {
    sku: 'HEXARELIN-5MG-3ML',
    name: 'Hexarelin',
    peptideId: 'hexarelin',
    doseMg: 5,
    volumeMl: 3,
    category: 'growth_factor',
    isBlend: false,
    description: 'Strong GH secretagogue with cardioprotective properties. Supports growth hormone release and heart health.',
    priceUsd: 66.30,
    stockStatus: 'in_stock',
    bulkPrice: 59.50,
    bulkMinQty: 25,
    bulkSavePercent: 10,
    variants: [
      { label: '2mg - 3ML', value: '2mg-3ml' },
      { label: '5mg - 3ML', value: '5mg-3ml' },
    ],
    defaultVariant: '5mg-3ml',
    vialType: '3ML',
  },
  {
    sku: 'IGF1LR3-0.01MG-3ML',
    name: 'IGF-1LR3',
    peptideId: 'igf1-lr3',
    doseMg: 0.01,
    volumeMl: 3,
    category: 'growth_factor',
    isBlend: false,
    description: 'Long-acting insulin-like growth factor that promotes muscle hyperplasia, recovery, and cellular growth.',
    priceUsd: 76.50,
    stockStatus: 'in_stock',
    bulkPrice: 69.70,
    bulkMinQty: 25,
    bulkSavePercent: 9,
    variants: [
      { label: '.01mg - 3ML', value: '0.01mg-3ml' },
      { label: '1mg - 3ML', value: '1mg-3ml' },
      { label: '1mg - 5ML', value: '1mg-5ml' },
    ],
    defaultVariant: '0.01mg-3ml',
    vialType: '3ML',
  },
  {
    sku: 'IPAMORELIN-5MG-3ML',
    name: 'Ipamorelin',
    peptideId: 'ipamorelin',
    doseMg: 5,
    volumeMl: 3,
    category: 'growth_factor',
    isBlend: false,
    description: 'Selective GH secretagogue with minimal side effects. Promotes growth hormone release without affecting cortisol or prolactin.',
    priceUsd: 76.50,
    stockStatus: 'in_stock',
    bulkPrice: 69.70,
    bulkMinQty: 25,
    bulkSavePercent: 9,
    variants: [
      { label: '5mg - 3ML', value: '5mg-3ml' },
      { label: '10mg - 3ML', value: '10mg-3ml' },
      { label: '15mg - 5ML', value: '15mg-5ml' },
    ],
    defaultVariant: '5mg-3ml',
    vialType: '3ML',
  },
  {
    sku: 'IPAMORELIN-SERMORELIN-5MG-3ML',
    name: 'Ipamorelin / Sermorelin',
    peptideId: null,
    doseMg: 5,
    volumeMl: 3,
    category: 'growth_factor',
    isBlend: true,
    blendComponents: ['ipamorelin', 'sermorelin'],
    description: 'Complementary GH blend that stimulates both GHRP and GHRH pathways for balanced growth hormone optimization.',
    priceUsd: 54.40,
    stockStatus: 'in_stock',
    bulkPrice: 49.30,
    bulkMinQty: 25,
    bulkSavePercent: 9,
    variants: [
      { label: '5mg/5mg - 3ML', value: '5mg-5mg-3ml' },
      { label: '10mg/10mg - 3ML', value: '10mg-10mg-3ml' },
    ],
    defaultVariant: '5mg-5mg-3ml',
    vialType: '3ML',
  },
  {
    sku: 'KISSPEPTIN-5MG-3ML',
    name: 'Kisspeptin',
    peptideId: 'kisspeptin-10',
    doseMg: 5,
    volumeMl: 3,
    category: 'hormonal',
    isBlend: false,
    description: 'Hypothalamic peptide that stimulates GnRH release. Supports reproductive hormone balance and fertility.',
    priceUsd: 76.50,
    stockStatus: 'in_stock',
    bulkPrice: 69.70,
    bulkMinQty: 25,
    bulkSavePercent: 9,
    variants: [
      { label: '5mg - 3ML', value: '5mg-3ml' },
      { label: '10mg - 3ML', value: '10mg-3ml' },
    ],
    defaultVariant: '5mg-3ml',
    vialType: '3ML',
  },
  {
    sku: 'KLOW-BPC157-GHKCU-TB500-KPV-5ML',
    name: 'KLOW BPC-157 GHK-CU TB-500 KPV',
    peptideId: null,
    doseMg: 10,
    volumeMl: 5,
    category: 'blend',
    isBlend: true,
    blendComponents: ['bpc-157', 'ghk-cu', 'tb-500', 'kpv'],
    description: 'Comprehensive repair and immune blend combining tissue healing, skin rejuvenation, and anti-inflammatory support.',
    priceUsd: 272.00,
    stockStatus: 'in_stock',
    bulkPrice: 244.80,
    bulkMinQty: 25,
    bulkSavePercent: 10,
    variants: [
      { label: '10mg/50mg/10mg/10mg - 3ML', value: '10mg-50mg-10mg-10mg-3ml' },
      { label: '10mg/70mg/10mg/10mg - 5ML', value: '10mg-70mg-10mg-10mg-5ml' },
    ],
    defaultVariant: '10mg-70mg-10mg-10mg-5ml',
    vialType: '5ML',
  },
  {
    sku: 'KPV-5MG-3ML',
    name: 'KPV',
    peptideId: 'kpv',
    doseMg: 5,
    volumeMl: 3,
    category: 'immune',
    isBlend: false,
    description: 'Anti-inflammatory tripeptide derived from alpha-MSH. Supports gut health and reduces systemic inflammation.',
    priceUsd: 85.00,
    stockStatus: 'in_stock',
    bulkPrice: 76.50,
    bulkMinQty: 25,
    bulkSavePercent: 10,
    variants: [
      { label: '5mg - 3ML', value: '5mg-3ml' },
      { label: '10mg - 3ML', value: '10mg-3ml' },
    ],
    defaultVariant: '5mg-3ml',
    vialType: '3ML',
  },
  {
    sku: 'LC120-10MG-3ML',
    name: 'LC-120',
    peptideId: 'lc-120',
    doseMg: 10,
    volumeMl: 3,
    category: 'neuropeptide',
    isBlend: false,
    description: 'Neuropeptide supporting cognitive clarity, mood regulation, and neuroplasticity for enhanced mental performance.',
    priceUsd: 100.30,
    stockStatus: 'out_of_stock',
    bulkPrice: 90.10,
    bulkMinQty: 25,
    bulkSavePercent: 10,
    variants: [{ label: '10mg - 3ML', value: '10mg-3ml' }],
    defaultVariant: '10mg-3ml',
    vialType: '3ML',
  },
  {
    sku: 'LL37-5MG-3ML',
    name: 'LL-37',
    peptideId: 'll-37',
    doseMg: 5,
    volumeMl: 3,
    category: 'immune',
    isBlend: false,
    description: 'Antimicrobial peptide that supports innate immune defense and helps combat biofilm-related infections.',
    priceUsd: 100.30,
    stockStatus: 'in_stock',
    bulkPrice: 90.10,
    bulkMinQty: 25,
    bulkSavePercent: 10,
    variants: [{ label: '5mg - 3ML', value: '5mg-3ml' }],
    defaultVariant: '5mg-3ml',
    vialType: '3ML',
  },
  {
    sku: 'MELANOTAN1-10MG-3ML',
    name: 'Melanotan 1',
    peptideId: 'melanotan-1',
    doseMg: 10,
    volumeMl: 3,
    category: 'hormonal',
    isBlend: false,
    description: 'Melanocortin receptor agonist that stimulates melanin production for natural UV-protective skin darkening.',
    priceUsd: 68.00,
    stockStatus: 'in_stock',
    bulkPrice: 61.20,
    bulkMinQty: 25,
    bulkSavePercent: 10,
    variants: [{ label: '10mg - 3ML', value: '10mg-3ml' }],
    defaultVariant: '10mg-3ml',
    vialType: '3ML',
  },
  {
    sku: 'MGF-2MG-3ML',
    name: 'MGF',
    peptideId: 'mgf',
    doseMg: 2,
    volumeMl: 3,
    category: 'growth_factor',
    isBlend: false,
    description: 'Mechano Growth Factor that activates satellite cells for localized muscle repair and growth after exercise or injury.',
    priceUsd: 66.30,
    stockStatus: 'in_stock',
    variants: [{ label: '2mg - 3ML', value: '2mg-3ml' }],
    defaultVariant: '2mg-3ml',
    vialType: '3ML',
  },
  {
    sku: 'MOTSC-10MG-3ML',
    name: 'MOTS-C',
    peptideId: 'mots-c',
    doseMg: 10,
    volumeMl: 3,
    category: 'metabolic',
    isBlend: false,
    description: 'Mitochondrial-derived peptide that enhances metabolic flexibility, exercise capacity, and cellular energy production.',
    priceUsd: 91.80,
    stockStatus: 'in_stock',
    bulkPrice: 83.30,
    bulkMinQty: 25,
    bulkSavePercent: 9,
    variants: [
      { label: '10mg - 3ML', value: '10mg-3ml' },
      { label: '40mg - 3ML', value: '40mg-3ml' },
      { label: '50mg - 5ML', value: '50mg-5ml' },
    ],
    defaultVariant: '10mg-3ml',
    vialType: '3ML',
  },
  {
    sku: 'MT2-10MG-3ML',
    name: 'MT-2 (Melanotan 2 Acetate)',
    peptideId: 'melanotan-2',
    doseMg: 10,
    volumeMl: 3,
    category: 'hormonal',
    isBlend: false,
    description: 'Melanocortin agonist that promotes tanning, may reduce appetite, and supports libido enhancement.',
    priceUsd: 74.80,
    stockStatus: 'in_stock',
    bulkPrice: 68.00,
    bulkMinQty: 25,
    bulkSavePercent: 9,
    variants: [{ label: '10mg - 3ML', value: '10mg-3ml' }],
    defaultVariant: '10mg-3ml',
    vialType: '3ML',
  },
  {
    sku: 'NAD-500MG-10ML',
    name: 'NAD+',
    peptideId: 'nad-plus',
    doseMg: 500,
    volumeMl: 10,
    category: 'bioregulator',
    isBlend: false,
    description: 'Essential coenzyme that supports cellular energy production, DNA repair, and healthy aging at the mitochondrial level.',
    priceUsd: 102.00,
    stockStatus: 'in_stock',
    bulkPrice: 91.80,
    bulkMinQty: 25,
    bulkSavePercent: 10,
    variants: [
      { label: '500mg - 10ML', value: '500mg-10ml' },
      { label: '1000mg - 10ML', value: '1000mg-10ml' },
    ],
    defaultVariant: '500mg-10ml',
    vialType: '10ML',
  },
  {
    sku: 'OXYTOCIN-2MG-3ML',
    name: 'Oxytocin',
    peptideId: 'oxytocin',
    doseMg: 2,
    volumeMl: 3,
    category: 'neuropeptide',
    isBlend: false,
    description: 'Neuropeptide that promotes social bonding, reduces stress and anxiety, and supports emotional well-being.',
    priceUsd: 69.70,
    stockStatus: 'in_stock',
    bulkPrice: 61.20,
    bulkMinQty: 25,
    bulkSavePercent: 12,
    variants: [{ label: '2mg - 3ML', value: '2mg-3ml' }],
    defaultVariant: '2mg-3ml',
    vialType: '3ML',
  },
  {
    sku: 'PEGMGF-2MG-3ML',
    name: 'PEG MGF',
    peptideId: 'peg-mgf',
    doseMg: 2,
    volumeMl: 3,
    category: 'growth_factor',
    isBlend: false,
    description: 'PEGylated Mechano Growth Factor with extended half-life for sustained muscle repair and systemic growth support.',
    priceUsd: 66.30,
    stockStatus: 'in_stock',
    bulkPrice: 59.50,
    bulkMinQty: 25,
    bulkSavePercent: 10,
    variants: [{ label: '2mg - 3ML', value: '2mg-3ml' }],
    defaultVariant: '2mg-3ml',
    vialType: '3ML',
  },
  {
    sku: 'PINEALON-5MG-3ML',
    name: 'Pinealon',
    peptideId: 'pinealon',
    doseMg: 5,
    volumeMl: 3,
    category: 'bioregulator',
    isBlend: false,
    description: 'Bioregulatory peptide that supports brain cell protection, cognitive function, and healthy sleep-wake cycles.',
    priceUsd: 66.30,
    stockStatus: 'in_stock',
    bulkPrice: 59.50,
    bulkMinQty: 25,
    bulkSavePercent: 10,
    variants: [
      { label: '5mg - 3ML', value: '5mg-3ml' },
      { label: '10mg - 3ML', value: '10mg-3ml' },
      { label: '20mg - 3ML', value: '20mg-3ml' },
    ],
    defaultVariant: '5mg-3ml',
    vialType: '3ML',
  },
  {
    sku: 'PT141-10MG-3ML',
    name: 'PT-141',
    peptideId: 'pt-141',
    doseMg: 10,
    volumeMl: 3,
    category: 'hormonal',
    isBlend: false,
    description: 'Melanocortin receptor agonist that works centrally to enhance sexual arousal and desire in both men and women.',
    priceUsd: 69.70,
    stockStatus: 'in_stock',
    bulkPrice: 61.20,
    bulkMinQty: 25,
    bulkSavePercent: 12,
    variants: [{ label: '10mg - 3ML', value: '10mg-3ml' }],
    defaultVariant: '10mg-3ml',
    vialType: '3ML',
  },
  {
    sku: 'PT141-KISSPEPTIN-PINEALON-5ML',
    name: 'PT-141 / Kisspeptin / Pinealon',
    peptideId: null,
    doseMg: 5,
    volumeMl: 5,
    category: 'hormonal',
    isBlend: true,
    blendComponents: ['pt-141', 'kisspeptin-10', 'pinealon'],
    description: 'Comprehensive hormonal blend supporting sexual health, reproductive function, and neuroprotection.',
    priceUsd: 137.70,
    stockStatus: 'in_stock',
    bulkPrice: 124.10,
    bulkMinQty: 25,
    bulkSavePercent: 10,
    variants: [{ label: '5mg/2mg/3mg - 5ML', value: '5mg-2mg-3mg-5ml' }],
    defaultVariant: '5mg-2mg-3mg-5ml',
    vialType: '5ML',
  },
  {
    sku: 'RTA-5MG-3ML',
    name: 'RTA',
    peptideId: null,
    doseMg: 5,
    volumeMl: 3,
    category: 'metabolic',
    isBlend: false,
    description: 'Triple-agonist GIP/GLP-1/glucagon receptor peptide for advanced metabolic support and significant weight management.',
    priceUsd: 136.00,
    stockStatus: 'in_stock',
    bulkPrice: 127.50,
    bulkMinQty: 25,
    bulkSavePercent: 6,
    variants: [
      { label: '5mg - 3ML', value: '5mg-3ml' },
      { label: '10mg - 3ML', value: '10mg-3ml' },
      { label: '15mg - 3ML', value: '15mg-3ml' },
      { label: '20mg - 3ML', value: '20mg-3ml' },
      { label: '30mg - 3ML', value: '30mg-3ml' },
      { label: '30mg - 5ML', value: '30mg-5ml' },
      { label: '40mg - 3ML', value: '40mg-3ml' },
      { label: '50mg - 3ML', value: '50mg-3ml' },
      { label: '60mg - 3ML', value: '60mg-3ml' },
      { label: '100mg - 10ML', value: '100mg-10ml' },
    ],
    defaultVariant: '5mg-3ml',
    vialType: '3ML',
  },
  {
    sku: 'SELANK-5MG-3ML',
    name: 'Selank',
    peptideId: 'selank',
    doseMg: 5,
    volumeMl: 3,
    category: 'neuropeptide',
    isBlend: false,
    description: 'Anxiolytic neuropeptide that reduces anxiety and enhances cognitive function without sedation or dependency.',
    priceUsd: 52.70,
    stockStatus: 'in_stock',
    bulkPrice: 47.60,
    bulkMinQty: 25,
    bulkSavePercent: 10,
    variants: [
      { label: '5mg - 3ML', value: '5mg-3ml' },
      { label: '11mg - 3ML', value: '11mg-3ml' },
    ],
    defaultVariant: '5mg-3ml',
    vialType: '3ML',
  },
  {
    sku: 'SELANK-SEMAX-5MG-3ML',
    name: 'Selank | Semax',
    peptideId: null,
    doseMg: 5,
    volumeMl: 3,
    category: 'neuropeptide',
    isBlend: true,
    blendComponents: ['selank', 'semax'],
    description: 'Nootropic blend combining anxiolytic and cognitive-enhancing neuropeptides for focus, clarity, and stress resilience.',
    priceUsd: 76.50,
    stockStatus: 'in_stock',
    bulkPrice: 69.70,
    bulkMinQty: 25,
    bulkSavePercent: 9,
    variants: [{ label: '5mg/5mg - 3ML', value: '5mg-5mg-3ml' }],
    defaultVariant: '5mg-5mg-3ml',
    vialType: '3ML',
  },
  {
    sku: 'SEMAX-5MG-3ML',
    name: 'Semax',
    peptideId: 'semax',
    doseMg: 5,
    volumeMl: 3,
    category: 'neuropeptide',
    isBlend: false,
    description: 'Nootropic peptide that enhances BDNF expression, cognitive performance, and neuroprotection.',
    priceUsd: 42.50,
    stockStatus: 'in_stock',
    bulkPrice: 39.10,
    bulkMinQty: 25,
    bulkSavePercent: 8,
    variants: [
      { label: '5mg - 3ML', value: '5mg-3ml' },
      { label: '11mg - 3ML', value: '11mg-3ml' },
    ],
    defaultVariant: '5mg-3ml',
    vialType: '3ML',
  },
  {
    sku: 'SERMORELIN-5MG-3ML',
    name: 'Sermorelin',
    peptideId: 'sermorelin',
    doseMg: 5,
    volumeMl: 3,
    category: 'growth_factor',
    isBlend: false,
    description: 'GHRH analog that stimulates natural growth hormone production. Supports anti-aging, sleep quality, and body composition.',
    priceUsd: 76.50,
    stockStatus: 'in_stock',
    bulkPrice: 69.70,
    bulkMinQty: 25,
    bulkSavePercent: 9,
    variants: [
      { label: '5mg - 3ML', value: '5mg-3ml' },
      { label: '9mg - 5ML', value: '9mg-5ml' },
      { label: '10mg - 3ML', value: '10mg-3ml' },
    ],
    defaultVariant: '5mg-3ml',
    vialType: '3ML',
  },
  {
    sku: 'SMA-5MG-3ML',
    name: 'SMA',
    peptideId: 'glp1-semaglutide',
    doseMg: 5,
    volumeMl: 3,
    category: 'metabolic',
    isBlend: false,
    description: 'Semaglutide GLP-1 receptor agonist for appetite suppression, blood sugar regulation, and sustainable weight loss.',
    priceUsd: 117.30,
    stockStatus: 'in_stock',
    bulkPrice: 110.50,
    bulkMinQty: 25,
    bulkSavePercent: 6,
    variants: [
      { label: '5mg - 3ML', value: '5mg-3ml' },
      { label: '10mg - 3ML', value: '10mg-3ml' },
      { label: '15mg - 3ML', value: '15mg-3ml' },
      { label: '20mg - 3ML', value: '20mg-3ml' },
      { label: '30mg - 3ML', value: '30mg-3ml' },
    ],
    defaultVariant: '5mg-3ml',
    vialType: '3ML',
  },
  {
    sku: 'SLUPP332-5MG-3ML',
    name: 'SLU-PP-332',
    peptideId: 'slu-pp-332',
    doseMg: 5,
    volumeMl: 3,
    category: 'metabolic',
    isBlend: false,
    description: 'Exercise mimetic compound that activates ERR pathways to enhance endurance and metabolic capacity.',
    priceUsd: 91.80,
    stockStatus: 'in_stock',
    bulkPrice: 83.30,
    bulkMinQty: 25,
    bulkSavePercent: 9,
    variants: [{ label: '5mg - 3ML', value: '5mg-3ml' }],
    defaultVariant: '5mg-3ml',
    vialType: '3ML',
  },
  {
    sku: 'SNAP8-10MG-3ML',
    name: 'SNAP-8',
    peptideId: 'snap-8',
    doseMg: 10,
    volumeMl: 3,
    category: 'repair',
    isBlend: false,
    description: 'Neuropeptide that relaxes facial muscles to reduce expression lines and wrinkles. A topical anti-aging solution.',
    priceUsd: 100.30,
    stockStatus: 'in_stock',
    bulkPrice: 90.10,
    bulkMinQty: 25,
    bulkSavePercent: 10,
    variants: [{ label: '10mg - 3ML', value: '10mg-3ml' }],
    defaultVariant: '10mg-3ml',
    vialType: '3ML',
  },
  {
    sku: 'SS31-10MG-3ML',
    name: 'SS-31',
    peptideId: 'elamipretide',
    doseMg: 10,
    volumeMl: 3,
    category: 'bioregulator',
    isBlend: false,
    description: 'Mitochondria-targeted peptide that protects against oxidative stress and supports cellular energy production.',
    priceUsd: 76.50,
    stockStatus: 'in_stock',
    bulkPrice: 69.70,
    bulkMinQty: 25,
    bulkSavePercent: 9,
    variants: [
      { label: '10mg - 3ML', value: '10mg-3ml' },
      { label: '50mg - 3ML', value: '50mg-3ml' },
    ],
    defaultVariant: '10mg-3ml',
    vialType: '3ML',
  },
  {
    sku: 'TB500-5MG-3ML',
    name: 'TB-500',
    peptideId: 'tb-500',
    doseMg: 5,
    volumeMl: 3,
    category: 'repair',
    isBlend: false,
    description: 'Thymosin Beta-4 fragment that promotes systemic tissue repair, reduces inflammation, and supports flexibility.',
    priceUsd: 83.30,
    stockStatus: 'in_stock',
    bulkPrice: 73.10,
    bulkMinQty: 25,
    bulkSavePercent: 12,
    variants: [
      { label: '5mg - 3ML', value: '5mg-3ml' },
      { label: '10mg - 3ML', value: '10mg-3ml' },
      { label: '15mg - 5ML', value: '15mg-5ml' },
    ],
    defaultVariant: '5mg-3ml',
    vialType: '3ML',
  },
  {
    sku: 'TESAMORELIN-5MG-3ML',
    name: 'Tesamorelin',
    peptideId: 'tesamorelin',
    doseMg: 5,
    volumeMl: 3,
    category: 'growth_factor',
    isBlend: false,
    description: 'FDA-studied GHRH analog that reduces visceral fat and stimulates natural growth hormone release.',
    priceUsd: 69.70,
    stockStatus: 'in_stock',
    bulkPrice: 61.20,
    bulkMinQty: 25,
    bulkSavePercent: 12,
    variants: [
      { label: '5mg - 3ML', value: '5mg-3ml' },
      { label: '10mg - 3ML', value: '10mg-3ml' },
      { label: '15mg - 5ML', value: '15mg-5ml' },
      { label: '20mg - 3ML', value: '20mg-3ml' },
    ],
    defaultVariant: '5mg-3ml',
    vialType: '3ML',
  },
  {
    sku: 'TESAMORELIN-IPAMORELIN-5MG-3ML',
    name: 'Tesamorelin | Ipamorelin',
    peptideId: null,
    doseMg: 5,
    volumeMl: 3,
    category: 'growth_factor',
    isBlend: true,
    blendComponents: ['tesamorelin', 'ipamorelin'],
    description: 'Powerful GH combination targeting visceral fat reduction with clean growth hormone amplification.',
    priceUsd: 103.70,
    stockStatus: 'in_stock',
    bulkPrice: 93.33,
    bulkMinQty: 25,
    bulkSavePercent: 10,
    variants: [
      { label: '5mg/5mg - 3ML', value: '5mg-5mg-3ml' },
      { label: '10mg/10mg - 3ML', value: '10mg-10mg-3ml' },
      { label: '12mg/6mg - 5ML', value: '12mg-6mg-5ml' },
    ],
    defaultVariant: '5mg-5mg-3ml',
    vialType: '3ML',
  },
  {
    sku: 'THYMALIN-10MG-3ML',
    name: 'Thymalin',
    peptideId: 'thymalin',
    doseMg: 10,
    volumeMl: 3,
    category: 'immune',
    isBlend: false,
    description: 'Thymic peptide that restores immune function and supports T-cell maturation for balanced immune defense.',
    priceUsd: 59.50,
    stockStatus: 'in_stock',
    bulkPrice: 54.40,
    bulkMinQty: 25,
    bulkSavePercent: 9,
    variants: [{ label: '10mg - 3ML', value: '10mg-3ml' }],
    defaultVariant: '10mg-3ml',
    vialType: '3ML',
  },
  {
    sku: 'THYMOSINALPHA1-5MG-3ML',
    name: 'Thymosin Alpha 1',
    peptideId: 'thymosin-alpha1',
    doseMg: 5,
    volumeMl: 3,
    category: 'immune',
    isBlend: false,
    description: 'Immune-modulating peptide that enhances T-cell function and supports defense against infections.',
    priceUsd: 100.30,
    stockStatus: 'in_stock',
    bulkPrice: 90.10,
    bulkMinQty: 25,
    bulkSavePercent: 10,
    variants: [
      { label: '5mg - 3ML', value: '5mg-3ml' },
      { label: '10mg - 3ML', value: '10mg-3ml' },
    ],
    defaultVariant: '5mg-3ml',
    vialType: '3ML',
  },
  {
    sku: 'THYMOSINALPHA1-THYMULIN-5ML',
    name: 'Thymosin Alpha 1 | Thymulin',
    peptideId: null,
    doseMg: 10,
    volumeMl: 5,
    category: 'immune',
    isBlend: true,
    blendComponents: ['thymosin-alpha1', 'thymulin'],
    description: 'Dual thymic peptide blend for comprehensive immune system restoration and defense optimization.',
    priceUsd: 130.90,
    stockStatus: 'in_stock',
    bulkPrice: 117.30,
    bulkMinQty: 25,
    bulkSavePercent: 10,
    variants: [{ label: '10mg/6mg - 5ML', value: '10mg-6mg-5ml' }],
    defaultVariant: '10mg-6mg-5ml',
    vialType: '5ML',
  },
  {
    sku: 'TRZ-5MG-3ML',
    name: 'TRZ',
    peptideId: 'glp1-tirzepatide',
    doseMg: 5,
    volumeMl: 3,
    category: 'metabolic',
    isBlend: false,
    description: 'Tirzepatide dual GIP/GLP-1 receptor agonist for powerful appetite suppression and blood sugar regulation.',
    priceUsd: 122.40,
    stockStatus: 'in_stock',
    bulkPrice: 115.60,
    bulkMinQty: 25,
    bulkSavePercent: 6,
    variants: [
      { label: '5mg - 3ML', value: '5mg-3ml' },
      { label: '10mg - 3ML', value: '10mg-3ml' },
      { label: '15mg - 3ML', value: '15mg-3ml' },
      { label: '20mg - 3ML', value: '20mg-3ml' },
      { label: '30mg - 3ML', value: '30mg-3ml' },
      { label: '40mg - 3ML', value: '40mg-3ml' },
      { label: '45mg - 3ML', value: '45mg-3ml' },
      { label: '50mg - 3ML', value: '50mg-3ml' },
      { label: '60mg - 3ML', value: '60mg-3ml' },
      { label: '60mg - 5ML', value: '60mg-5ml' },
      { label: '100mg - 10ML', value: '100mg-10ml' },
    ],
    defaultVariant: '5mg-3ml',
    vialType: '3ML',
  },
  {
    sku: 'VIP-5MG-3ML',
    name: 'VIP',
    peptideId: 'vip',
    doseMg: 5,
    volumeMl: 3,
    category: 'neuropeptide',
    isBlend: false,
    description: 'Vasoactive Intestinal Peptide that supports respiratory, gut, and neurological health through anti-inflammatory action.',
    priceUsd: 83.30,
    stockStatus: 'low_stock',
    bulkPrice: 76.50,
    bulkMinQty: 25,
    bulkSavePercent: 8,
    variants: [
      { label: '5mg - 3ML', value: '5mg-3ml' },
      { label: '10mg - 3ML', value: '10mg-3ml' },
    ],
    defaultVariant: '5mg-3ml',
    vialType: '3ML',
  },
]

// ===================================================
// Helper functions
// ===================================================

export function getAllProducts(): ShopProduct[] {
  return PRODUCT_CATALOG
}

export function getProductBySku(sku: string): ShopProduct | null {
  return PRODUCT_CATALOG.find(p => p.sku === sku) || null
}

export function getProductsByCategory(category: ProductCategory): ShopProduct[] {
  return PRODUCT_CATALOG.filter(p => p.category === category)
}

export function getProductsByPeptideId(peptideId: string): ShopProduct[] {
  return PRODUCT_CATALOG.filter(p => p.peptideId === peptideId)
}

export function searchProducts(query: string): ShopProduct[] {
  const normalizedQuery = query.toLowerCase()
  return PRODUCT_CATALOG.filter(p =>
    p.name.toLowerCase().includes(normalizedQuery) ||
    p.sku.toLowerCase().includes(normalizedQuery)
  )
}

export function getBlends(): ShopProduct[] {
  return PRODUCT_CATALOG.filter(p => p.isBlend)
}

export function getUniquePeptideIds(): string[] {
  const ids = new Set<string>()
  PRODUCT_CATALOG.forEach(p => {
    if (p.peptideId) ids.add(p.peptideId)
  })
  return Array.from(ids)
}

export function getCategoryDisplayName(category: ProductCategory): string {
  const names: Record<ProductCategory, string> = {
    growth_factor: 'Growth Factors',
    repair: 'Repair & Recovery',
    metabolic: 'Metabolic & Weight Loss',
    bioregulator: 'Bioregulators',
    neuropeptide: 'Neuropeptides',
    immune: 'Immune Support',
    hormonal: 'Hormonal',
    blend: 'Blends',
    accessory: 'Accessories',
    wellness_supplement: 'Wellness Supplements',
  }
  return names[category]
}

export function getCategoriesWithCounts(): { category: ProductCategory; count: number; displayName: string }[] {
  const categories: ProductCategory[] = ['metabolic', 'growth_factor', 'repair', 'bioregulator', 'neuropeptide', 'immune', 'hormonal', 'blend', 'accessory']
  return categories.map(category => ({
    category,
    count: getProductsByCategory(category).length,
    displayName: getCategoryDisplayName(category),
  })).filter(c => c.count > 0)
}

export function getUniqueVialTypes(): string[] {
  const types = new Set<string>()
  PRODUCT_CATALOG.forEach(p => {
    if (p.vialType) types.add(p.vialType)
  })
  return Array.from(types).sort()
}

export function getProductsByStockStatus(status: StockStatus): ShopProduct[] {
  return PRODUCT_CATALOG.filter(p => p.stockStatus === status)
}

export function getProductsByVialType(vialType: string): ShopProduct[] {
  return PRODUCT_CATALOG.filter(p => p.vialType === vialType)
}

// ===================================================
// HSA/FSA LMN ELIGIBILITY
// ===================================================

const LMN_EXCLUDED_CATEGORIES: ProductCategory[] = ['accessory']

export function isLmnEligible(product: ShopProduct): boolean {
  return !LMN_EXCLUDED_CATEGORIES.includes(product.category)
}

export function isLmnEligibleCategory(category: ProductCategory): boolean {
  return !LMN_EXCLUDED_CATEGORIES.includes(category)
}

export function getLmnEligibleProducts(): ShopProduct[] {
  return PRODUCT_CATALOG.filter(isLmnEligible)
}
