import { DosingProduct } from '../types';

export const DOSING_PRODUCTS: Record<string, DosingProduct> = {
  semaglutide: {
    id: 'semaglutide',
    name: 'Semaglutide',
    category: 'labeled_reference',
    isFdaApprovedForMaintenance: true,
    requiresProviderEscalation: false,
    concentration: {
      vialSizeMg: 5,
      diluentVolumeMl: 3,
      mgPerMl: 1.67,
      mcgPerUnitU100: 16.7,
    },
  },
  tirzepatide: {
    id: 'tirzepatide',
    name: 'Tirzepatide',
    category: 'labeled_reference',
    isFdaApprovedForMaintenance: true,
    requiresProviderEscalation: false,
    concentration: {
      vialSizeMg: 20,
      diluentVolumeMl: 3,
      mgPerMl: 6.67,
      mcgPerUnitU100: 66.7,
    },
  },
  retatrutide: {
    id: 'retatrutide',
    name: 'Retatrutide',
    category: 'investigational',
    isFdaApprovedForMaintenance: false,
    requiresProviderEscalation: true,
    concentration: {
      vialSizeMg: 20,
      diluentVolumeMl: 3,
      mgPerMl: 6.67,
      mcgPerUnitU100: 66.7,
    },
  },
  'tesa-ipa': {
    id: 'tesa-ipa',
    name: 'Tesamorelin / Ipamorelin',
    category: 'investigational',
    isFdaApprovedForMaintenance: false,
    requiresProviderEscalation: true,
    concentration: {
      isBlend: true,
      vialSizeMg: 12,
      diluentVolumeMl: 5,
      mgPerMl: 2.4, // Tesamorelin
      mcgPerUnitU100: 24,
      secondaryVialSizeMg: 6,
      secondaryMgPerMl: 1.2, // Ipamorelin
      secondaryMcgPerUnitU100: 12,
    },
  },
  'ghk-cu': {
    id: 'ghk-cu',
    name: 'GHK-Cu',
    category: 'conversion_only',
    isFdaApprovedForMaintenance: false,
    requiresProviderEscalation: true,
    concentration: {
      vialSizeMg: 100,
      diluentVolumeMl: 3,
      mgPerMl: 33.3,
      mcgPerUnitU100: 333,
    },
  },
  'cjc-ipa': {
    id: 'cjc-ipa',
    name: 'CJC1295 / Ipamorelin',
    category: 'conversion_only',
    isFdaApprovedForMaintenance: false,
    requiresProviderEscalation: true,
    concentration: {
      isBlend: true,
      vialSizeMg: 10,
      diluentVolumeMl: 3,
      mgPerMl: 3.33,
      mcgPerUnitU100: 33.3,
      secondaryVialSizeMg: 10,
      secondaryMgPerMl: 3.33,
      secondaryMcgPerUnitU100: 33.3,
    },
  },
  'nad-plus': {
    id: 'nad-plus',
    name: 'NAD+',
    category: 'conversion_only',
    isFdaApprovedForMaintenance: false,
    requiresProviderEscalation: true,
    concentration: {
      vialSizeMg: 1000,
      diluentVolumeMl: 10,
      mgPerMl: 100,
      mcgPerUnitU100: 1000,
    },
  },
  'semax-selank': {
    id: 'semax-selank',
    name: 'Semax / Selank',
    category: 'conversion_only',
    isFdaApprovedForMaintenance: false,
    requiresProviderEscalation: true,
    concentration: {
      isBlend: true,
      vialSizeMg: 5,
      diluentVolumeMl: 3,
      mgPerMl: 1.67,
      mcgPerUnitU100: 16.7,
      secondaryVialSizeMg: 5,
      secondaryMgPerMl: 1.67,
      secondaryMcgPerUnitU100: 16.7,
    },
  },
  'bpc157-tb500': {
    id: 'bpc157-tb500',
    name: 'BPC157 / TB500',
    category: 'conversion_only',
    isFdaApprovedForMaintenance: false,
    requiresProviderEscalation: true,
    concentration: {
      isBlend: true,
      vialSizeMg: 10,
      diluentVolumeMl: 3,
      mgPerMl: 3.33,
      mcgPerUnitU100: 33.3,
      secondaryVialSizeMg: 10,
      secondaryMgPerMl: 3.33,
      secondaryMcgPerUnitU100: 33.3,
    },
  },
  'melanotan-2': {
    id: 'melanotan-2',
    name: 'Melanotan 2',
    category: 'conversion_only',
    isFdaApprovedForMaintenance: false,
    requiresProviderEscalation: true,
    concentration: {
      vialSizeMg: 10,
      diluentVolumeMl: 3,
      mgPerMl: 3.33,
      mcgPerUnitU100: 33.3,
    },
  },
};
